services:
  - type: web
    name: yogie-corporation
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CONTACT_TO
        value: Liptonmourin@yogiecorp.com, akhtar@yogiecorp.com, yogie@yogiecorp.com
      - key: CONTACT_FROM
        value: yogie@yogiecorp.com
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
